CREATE TABLE [dbo].[ProjectUsers]
(
	[Id] INT NOT NULL IDENTITY PRIMARY KEY, 
	[ProjectId] INT NOT NULL,
	[UserId] INT NOT NULL, 
	FOREIGN KEY (ProjectId) REFERENCES Projects (Id)  ON DELETE CASCADE, 
	FOREIGN KEY (UserId) REFERENCES Users (Id)  ON DELETE CASCADE, 
)
